apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: lnd2020core 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lnd2020core
    spec:
      containers:
        - name: lnd2020core
          image: lnd2020acr.azurecr.io/lnd2020core
          ports:
          - containerPort: 80